
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FurnitureStore.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Furniture
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Furniture()
    {

        this.OrderDetails = new HashSet<OrderDetail>();

        this.ShoppingCarts = new HashSet<ShoppingCart>();

    }


    public int furnitureId { get; set; }

    public int categoryId { get; set; }

    public string furnitureTitle { get; set; }

    public Nullable<double> furniturePrice { get; set; }

    public Nullable<int> furnitureInStock { get; set; }

    public Nullable<int> furnitureOnOrder { get; set; }

    public string images { get; set; }



    public virtual Category Category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }

}

}
