
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FurnitureStore.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail
{

    public int orderDetailsId { get; set; }

    public int furnitureId { get; set; }

    public int orderId { get; set; }

    public Nullable<double> furniturePrice { get; set; }

    public Nullable<double> quantity { get; set; }

    public string deliveryStatus { get; set; }



    public virtual Furniture Furniture { get; set; }

    public virtual Order Order { get; set; }

}

}
