
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FurnitureStore.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Payment
{

    public int paymentId { get; set; }

    public Nullable<int> orderId { get; set; }

    public Nullable<int> paymentTypeId { get; set; }

    public Nullable<double> totalSum { get; set; }

    public Nullable<System.DateTime> paymentDate { get; set; }



    public virtual Order Order { get; set; }

    public virtual PaymentType PaymentType { get; set; }

}

}
